export const data = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 28,
    isActive: true,
    joinedDate: "2023-01-15",
    address: {
      street: "123 Main St",
      city: "New York",
      country: "USA",
    },
    interests: ["reading", "hiking", "photography"],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 34,
    isActive: false,
    joinedDate: "2022-11-03",
    address: {
      street: "456 Oak Ave",
      city: "London",
      country: "UK",
    },
    interests: ["cooking", "travel"],
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert.j@example.com",
    age: 22,
    isActive: true,
    joinedDate: "2023-05-20",
    address: {
      street: "789 Pine Rd",
      city: "Sydney",
      country: "Australia",
    },
    interests: ["gaming", "music"],
  },
  {
    id: 4,
    name: "Emily Wilson",
    email: "emily.w@example.com",
    age: 31,
    isActive: true,
    joinedDate: "2021-08-14",
    address: {
      street: "321 Elm Blvd",
      city: "Toronto",
      country: "Canada",
    },
    interests: ["yoga", "writing"],
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael.b@example.com",
    age: 45,
    isActive: false,
    joinedDate: "2020-03-10",
    address: {
      street: "654 Maple Ln",
      city: "Berlin",
      country: "Germany",
    },
    interests: ["cycling", "photography"],
  },
  {
    id: 6,
    name: "Sarah Davis",
    email: "sarah.d@example.com",
    age: 29,
    isActive: true,
    joinedDate: "2023-02-28",
    address: {
      street: "987 Cedar St",
      city: "Paris",
      country: "France",
    },
    interests: ["art", "fashion"],
  },
  {
    id: 7,
    name: "David Miller",
    email: "david.m@example.com",
    age: 38,
    isActive: true,
    joinedDate: "2022-07-19",
    address: {
      street: "135 Birch Ave",
      city: "Tokyo",
      country: "Japan",
    },
    interests: ["technology", "reading"],
  },
  {
    id: 8,
    name: "Lisa Taylor",
    email: "lisa.t@example.com",
    age: 27,
    isActive: false,
    joinedDate: "2023-04-05",
    address: {
      street: "246 Willow Dr",
      city: "Seoul",
      country: "South Korea",
    },
    interests: ["movies", "dancing"],
  },
  {
    id: 9,
    name: "James Wilson",
    email: "james.w@example.com",
    age: 41,
    isActive: true,
    joinedDate: "2021-12-12",
    address: {
      street: "864 Spruce Ct",
      city: "Mumbai",
      country: "India",
    },
    interests: ["cricket", "travel"],
  },
  {
    id: 10,
    name: "Emma Anderson",
    email: "emma.a@example.com",
    age: 33,
    isActive: true,
    joinedDate: "2022-09-25",
    address: {
      street: "579 Aspen Way",
      city: "São Paulo",
      country: "Brazil",
    },
    interests: ["music", "cooking"],
  },
];
